# Generated by Django 2.2.1 on 2019-05-09 08:52

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classify', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='FullWidth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('fullpic', models.ImageField(upload_to='fullwidth')),
                ('fyr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='furnitureapp.Classify')),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgname', models.CharField(max_length=16)),
                ('indexn', models.SmallIntegerField()),
                ('img', models.ImageField(upload_to='hotpic')),
                ('classifies', models.ManyToManyField(to='furnitureapp.Classify')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=26, null=True)),
                ('name', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=13, null=True)),
                ('message', models.TextField(max_length=660, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=16)),
                ('deti', models.CharField(max_length=16)),
                ('img', models.ImageField(upload_to='textimg')),
                ('fyr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='furnitureapp.Classify')),
            ],
        ),
        migrations.CreateModel(
            name='SingTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singimg', models.ImageField(upload_to='singtwo')),
                ('name', models.CharField(max_length=16)),
                ('sfor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='furnitureapp.FullWidth')),
                ('timgfy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='furnitureapp.TextPic')),
            ],
        ),
        migrations.CreateModel(
            name='FurnitureInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=90)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.CharField(max_length=26)),
                ('tagweb', models.URLField(max_length=36)),
                ('title', models.CharField(max_length=150)),
                ('descirbe', tinymce.models.HTMLField()),
                ('tofu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furnitureapp.Furniture')),
            ],
        ),
        migrations.CreateModel(
            name='Furnitureimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('furimg', models.ImageField(upload_to='hotpic')),
                ('index', models.SmallIntegerField()),
                ('fore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furnitureapp.Furniture')),
            ],
        ),
    ]
