# Generated by Django 2.2.1 on 2019-05-09 08:52

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aTitle', models.CharField(max_length=20)),
                ('aPublicTime', models.DateTimeField(auto_now=True)),
                ('aContent', tinymce.models.HTMLField()),
                ('aBackgroundImage', models.ImageField(upload_to='articleImages')),
                ('aReadNum', models.SmallIntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tName', models.CharField(default='家具', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tName', models.CharField(default='纹理会话', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserSell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uheaderImg', models.ImageField(upload_to='userHeaders')),
                ('uName', models.CharField(default='bh', max_length=20)),
                ('uPwd', models.CharField(default='000', max_length=10)),
                ('uType', models.CharField(default='sell', max_length=10)),
                ('uBrief', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cPublicPeople', models.CharField(max_length=20)),
                ('cEmail', models.EmailField(max_length=254)),
                ('cPhone', models.CharField(max_length=11)),
                ('cUrl', models.URLField()),
                ('cContent', models.CharField(max_length=500)),
                ('cArticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='aAuthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserSell'),
        ),
        migrations.AddField(
            model_name='article',
            name='aTag',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
        migrations.AddField(
            model_name='article',
            name='aType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Type'),
        ),
    ]
